-- Migration: Add client_transaction_id for end-to-end tracing
-- Date: 2025-12-03
-- Purpose: Enable MomoTerminal ↔ EasyMO transaction correlation

-- Add client_transaction_id to transactions table
ALTER TABLE transactions 
ADD COLUMN IF NOT EXISTS client_transaction_id UUID UNIQUE;

-- Add index for efficient lookups by client ID
CREATE INDEX IF NOT EXISTS idx_transactions_client_id 
ON transactions(client_transaction_id);

-- Add nonce tracking table for replay protection
CREATE TABLE IF NOT EXISTS webhook_nonces (
    nonce TEXT PRIMARY KEY,
    device_id TEXT NOT NULL,
    received_at TIMESTAMPTZ DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '5 minutes')
);

-- Index for cleanup of expired nonces
CREATE INDEX IF NOT EXISTS idx_webhook_nonces_expires 
ON webhook_nonces(expires_at);

-- Function to clean up expired nonces (run periodically)
CREATE OR REPLACE FUNCTION cleanup_expired_nonces()
RETURNS INTEGER AS $$
DECLARE
    deleted_count INTEGER;
BEGIN
    DELETE FROM webhook_nonces WHERE expires_at < NOW();
    GET DIAGNOSTICS deleted_count = ROW_COUNT;
    RETURN deleted_count;
END;
$$ LANGUAGE plpgsql;

-- Idempotency keys table for preventing duplicate processing
CREATE TABLE IF NOT EXISTS idempotency_keys (
    key TEXT PRIMARY KEY,
    result JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL
);

-- Index for idempotency key cleanup
CREATE INDEX IF NOT EXISTS idx_idempotency_expires 
ON idempotency_keys(expires_at);

-- Function to check and store idempotency key
CREATE OR REPLACE FUNCTION check_idempotency(
    p_key TEXT,
    p_ttl_seconds INTEGER DEFAULT 86400
)
RETURNS TABLE(is_duplicate BOOLEAN, cached_result JSONB) AS $$
DECLARE
    existing_result JSONB;
BEGIN
    -- Check for existing key
    SELECT result INTO existing_result
    FROM idempotency_keys
    WHERE key = p_key AND expires_at > NOW();
    
    IF existing_result IS NOT NULL THEN
        RETURN QUERY SELECT TRUE, existing_result;
    ELSE
        RETURN QUERY SELECT FALSE, NULL::JSONB;
    END IF;
END;
$$ LANGUAGE plpgsql;

-- Comment for documentation
COMMENT ON COLUMN transactions.client_transaction_id IS 
'UUID generated by MomoTerminal app for end-to-end transaction tracing';

COMMENT ON TABLE webhook_nonces IS 
'Tracks webhook nonces to prevent replay attacks. Nonces expire after 5 minutes.';

COMMENT ON TABLE idempotency_keys IS 
'Stores idempotency keys to prevent duplicate transaction processing.';
